
version: '2'

services:
  pg-master:
    build: '.'
    image: 'replication-cluster'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - '/var/lib/postgresql/data'
    expose:
      - '5432'
    ports:
      - '5433:5432'

  pg-slave:
    build: '.'
    image: 'replication-cluster'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
      - '/var/lib/postgresql/data'
    expose:
      - '5432'
    links:
      - 'pg-master'
    ports:
      - '5434:5432'
